### ISSUE TITLE
Pinned dependencies make it difficult/dangerous to use in existing venvs

### ISSUE THREAD

**Issue by xrotwang** [fmatter/lingtreemaps#2]
Pinning dependencies (see https://github.com/fmatter/lingtreemaps/blob/7eb76117f86a9adb18241054357765853a226547/setup.cfg#L33-L76) makes it difficult to use the package in existing virtual environments.

**Comment by xrotwang** [comment]
Hm. I think the pinned `pyproj` really messed with my gdal installation.

**Comment by fmatter** [comment]
I actually ran into problems with this very issue just yesterday :). Sorry about your gdal, I think I just did `pip3 freeze` when preparing for the first release.

**Comment by xrotwang** [comment]
Re-installing now still tries to install `pyproj==3.4` which isn't compatible with PROJ as installed with Ubuntu 20.04 according to https://pyproj4.github.io/pyproj/stable/installation.html#installing-from-source
Dunno where this comes from. geopandas maybe.

**Comment by xrotwang** [comment]
Could be: https://github.com/geopandas/geopandas/blob/047a5cd69bde2b8831d1cde78d59789f56958ce3/setup.py#L39

**Comment by fmatter** [comment]
I get `pyproj-3.2.1` in a fresh venv on python 3.7.13

**Comment by xrotwang** [comment]
Which Ubuntu are you on? And does `cldfviz.map` work for creating `png` maps for you?

**Comment by fmatter** [comment]
Ubuntu 20.04.5 LTS. I had to switch to python3.8 in order to install cartopy 0.21 (earlier versions require PROJ 8.0.0 -- https://github.com/SciTools/cartopy/issues/1879). 

Now I am getting

```
free(): invalid size
Aborted (core dumped)
```

**Comment by xrotwang** [comment]
Ok, so you can reproduce my problems :)

**Comment by xrotwang** [comment]
I'm out of ideas here. I re-installed libproj etc. several times, created a virtual with `--system-site-packages` to make sure `pyproj` or similar don't bring in their own `libproj` ... Didn't help.

**Comment by xrotwang** [comment]
Ok, `pip install "shapely<1.8"` fixed things for me. See also
https://stackoverflow.com/questions/71654190/cartopy-issue-with-extent-free-invalid-size
